spring:
  application:
    name: golf-courses
  datasource:
    url: jdbc:postgresql://localhost:5432/golfcourses
    username: golfcourses
    password: golfcourses
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 8080
